### ISSUE TITLE
有关super和self的问题

### ISSUE THREAD

**Issue by AnYuan** [BaiduHiDeviOS/iOS-puzzles#1]
``` Objective-C
    @implementation Son : Father
    - (id)init
    {
        self = [super init];
        if (self) {
            NSLog(@"%@", NSStringFromClass([self class]));
            NSLog(@"%@", NSStringFromClass([super class]));
        }
        return self;
    }
    @end
```

上面的代码会输出什么？why？

**Comment by iiiGlare** [comment]
我会，但我不说~ super 是个知识点~

**Comment by ghost** [comment]
两句输出语句均输出：Son

简单来说，self和super都是指向当前实例的，不同的是，`[self class]`会在当前类的方法列表中去找class这个方法，`[super class]`会直接开始在当前类的父类中去找calss这个方法，两者在找不到的时候，都会继续向祖先类查询class方法，最终到NSObject类。那么问题来了，由于我们在Father和Son中都没有去重写class这个方法，最终自然都会去执行NSObject中的class方法，结果也自然应该是一样的。至于为什么是Son，我们可以看看NSObject中class的实现：

```
- (Class)class {
    return object_getClass(self);
}
```

这就说的通了，返回的都是self的类型，self此处正好就是Son，因此结果就会输出Son。

证明：

如果我们在Father和Son中去重写class方法，结果：

```
2016-08-26 20:04:10.731 Self-Super[44225:11081811] Son  
2016-08-26 20:04:10.731 Self-Super[44225:11081811] Father
```

资料： http://chun.tips/blog/2014/11/05/bao-gen-wen-di-objective%5Bnil%5Dc-runtime(1)%5Bnil%5D-self-and-super/

不过我有个问题，class方法怎么重写呀。。。。。

**Comment by AnYuan** [comment]
``` objc
//Father
-(Class)class {
    return objc_getClass("Father");
}

//Son
-(Class)class {
    return objc_getClass("Son");
}
```

如果复写class方法，打印结果为：

```
Son
Father
```

我觉得这道题主要考察objc中方法传递顺序：
会先从实例方法开始查找方法实现，如果未实现到父类方法查找，一层层往上找，找到了`NSObject`, 因为`NSObject` 对class方法有实现：

``` objc
- (Class)class {
    return object_getClass(self);
}
```

其中self为Son实例对象，所以输出都为Son

顺便补充上objc 消息传递的完整过程：
1. 判断接受者是否为空？ 如果为空，调用nil-handler, 默认为什么都不做。
2. 检查class的方法调用cache，是否调用过此方法。
3. 检查方法列表是否有此方法，有则调用。
4. 检查父类方法列表是否有此方法，有则调用。（如果一直找不到会找到最根的父类如NSObject, NSProxy）
5. `resolveInstanceMethod:`
6. `forwardingTargetForSelector:` 此处不要返回`self`, 否则会产生循环。
7. `methodSignatureForSelector:`, 如果返回非nil，创建一个`NSInvocation` 并传递给`forwardInvocation`.
8. 调用`doesNotRecognizeSelector:` 默认实现为抛一个异常。
