### ISSUE TITLE
覆写 UIButton 的 - intrinsicContentSize 方法后，布局时 - intrinsicContentSize 被循环调用

### ISSUE THREAD

**Issue by iiiGlare** [BaiduHiDeviOS/iOS-puzzles#2]
感谢 @AnYuan 抛的玉，我来贡献一块砖~

这个问题是实际开发过程中遇到的，感觉有点意思，大家可以想想看~
我们基于 UIButton 实现了图片和文字垂直排版的 UIVerticalButton，需要覆写 - intrinsicContentSize 方法重新计算固有内容尺寸，我贴个简化代码：

``` objective-c
...
- (CGSize)intrinsicContentSize {
    NSString *title = [self titleForState:UIControlStateNormal];
    NSString *font = self.titleLabel.font;
    CGSize titleSize = [[[NSAttributedString alloc] initWithString:title attributes:@{NSFontAttributeName: font}] size];
    return titleSize;
}
...
```

然后使用该Button

``` objective-c
UIVerticalButton *button = [UIVerticalButton buttonWithType:UIButtonTypeCustom]
[button setTitle:@"Vertical Button" forState:UIControlStateNormal];
button.titleLabel.font = [UIFont systemFontOfSize:18.f];
...
```

此代码会导致布局时 - intrinsicContentSize 被循环调用，请问:
1 为什么？
2 如何解决？

PS: 此问题仅在iOS 7下出现~

**Comment by AnYuan** [comment]
单从贴出这段代码，不觉得有问题哇 @GlareCH

**Comment by goodman-capu** [comment]
没人回答吗 提示一下 代码死循环了😌

**Comment by iiiGlare** [comment]
1 为什么？
出问题的原因是在 - intrinsicContentSize 方法中调用 self.titleLabel，在iOS 7下，该语句会触发界面布局（可能是当时的一个bug），导致 - intrinsicContentSize 被调用，如此陷入循环。

咋看可能会感觉问题不大，比如反正iOS 8之后已经没问题了。但是不规范或者错误的布局代码，会很容易引起类似的问题，所以这类问题主要看的还是对布局的理解程度。

2 如何解决？
这个各位可以再想想

**Comment by AnYuan** [comment]
@GlareCH 那为什么调用self.titleLabel 会触发重新布局呢？

**Comment by AnYuan** [comment]
@GlareCH 如何解决的话，是不是可以放在`sizeThatFits:`中了
