### ISSUE TITLE
有关向对象发消息的安全性问题

### ISSUE THREAD

**Issue by goodman-capu** [BaiduHiDeviOS/iOS-puzzles#3]
碰到一个有关对对象发消息的安全性问题，拿出来分享一下

有下面这个方法：

``` objc
- (NSString *)testObject:(int)i {
    if (i % 3 != 0) {
        return [@(i) stringValue];
    } else {
        return nil;
    }
}
```

以下代码执行时会出现什么现象？

``` objc
for (int i = 1; i <= 3; i++) {
    NSLog(@"%d", [[self testObject:i] intValue]);
    NSLog(@"%@", [self testObject:i]);
}
```

**Comment by AnYuan** [comment]
输出应该为：
1
1
2
2
0
null

可以引用[这里](https://github.com/BaiduHiDeviOS/iOS-puzzles/issues/1) 我最后的一个关于方法调用步骤的解答， 如果对nil发方法调用，默认实现是直接返回的。
进一步，你提供的实例代码，当 `i = 3`时， 打印了两个nil的值。
当以`%d`打印时，nil 的值为 0， 当以`%@`打印时， nil的值为null。

这里可以引申下，OC中的几种空值`nil / Nil / NULL / NSNull`都是干嘛的，什么时候用。

可以参考[这篇文章](http://nshipster.com/nil/)
