### ISSUE TITLE
一个简单的问题，准备笔试的时候遇到的。

### ISSUE THREAD

**Issue by ghost** [BaiduHiDeviOS/iOS-puzzles#4]
```
    ................
    float a = .............
    ................

    printf("%f\n", a);

    a == 0 ? printf("equal\n") : printf("not equal\n");
```

程序输出： 

```
0.000000
not equal
Program ended with exit code: 0
```

Q1：上面程序为何输出a=0却又输出not equal？
Q2：怎么用程序判断一个float或者double类型的变量是否等于0？
Q3：为什么我们平时会写 

```
if (a == 0) {
        ...
    }
```

是否存在问题？

**Comment by ghost** [comment]
大家都觉得这个问题太简单了嘛            /(sad)               难怪我笔试那么low。。。。。。。

**Comment by AnYuan** [comment]
Q1：我觉得这道题目主要考察浮点数在计算机中的表示方法。当年看CSAPP中有介绍，如果感兴趣的同学可以重温下。

在swift 中 0.1 + 0.2 的输出为0.30000000000000004
计算机的二进制表达浮点数是不能精确表达的。

Q2：在程序中判断一个float或double类型是否等于0， 可以判断这个浮点数的绝对值小于一个极小值，如0.000001

Q3：如果a为浮点数，我们是不能这样判断的，如果整形则没问题。

**Comment by dourgulf** [comment]
这个主要就是浮点数的表示法, 计算机基础课程.

**Comment by ghost** [comment]
@dourgulf    所以大家平时判断浮点数是否等于0，都不是简单写成if (a == 0) ？

**Comment by dourgulf** [comment]
必须不是呀, ~
