### ISSUE TITLE
AutoLayout中，哪些约束条件会影响视图的宽度，哪些约束条件会影响视图的高度？

### ISSUE THREAD

**Issue by iiiGlare** [BaiduHiDeviOS/iOS-puzzles#7]
韩信点兵，多多益善~

**Comment by AnYuan** [comment]
视图本身的宽高约束

**Comment by ghost** [comment]
@AnYuan 视图本身的宽高约束固然会影响，不过没这么简单 
这个问题，是说原生的AutoLayout，还是说广义的布局问题中，影响视图宽高的因素呢？ @GlareCH

**Comment by AnYuan** [comment]
@nolol， @GlareCH 说有哪些约束会影响视图宽高，我说的是其中的两个。
