### ISSUE TITLE
是否可以在 @synchronized 的 body 中 return？

### ISSUE THREAD

**Issue by iiiGlare** [BaiduHiDeviOS/iOS-puzzles#8]
例如以下两种写法：

``` objective-c
- (id)getSomeObject {
    @synchronized(self) {
        return object;
    }
}
```

``` objective-c
- (id)getSomeObject {
    id result;
    @synchronized(self) {
        result = object;
    }
    return result;
}
```

哪种写法是对的？在 @synchronized 代码块中直接 return，是否存在锁问题？

**Comment by goodman-capu** [comment]
没人回答嘛。。。貌似可以？

**Comment by DemoCooky** [comment]
我的理解哈：这两种写法都是对的，使用时应该针对具体的场景，如果返回的object值会受其它线程影响时，使用第一种写法。

**Comment by nspangbo** [comment]
问题本身，是否可以在 @synchronized 的 body 中 return，答案是可以的。

@synchronized 是语法之外，一个 compile attribute 而已，最终代码会转化成
``` objective-c
@try {
    objc_sync_enter(obj);
    return object;
} @finally {
    objc_sync_exit(obj);    
}
```

但是第二种写法我认为本身就是错误的，之所以这样写，应该是为了实现获取 object 对象的线程安全需求，但是该写法将 object 的值赋予给一个局部变量之后，就离开了临界区，此时 object 的值是可能被其他线程改变的，导致 `return result` 的结果，并不是 object 的值，进而导致 getSomeObject 方法并不是线程安全的。

而如果本身就没有线程安全的需求，更不应该使用 @synchronized 了。
